# Generated by Django 5.0.1 on 2025-01-09 21:04

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('post_view', 'Post View'), ('post_like', 'Post Like'), ('story_view', 'Story View'), ('profile_view', 'Profile View'), ('search', 'Search'), ('message_sent', 'Message Sent'), ('login', 'Login'), ('video_watch', 'Video Watch'), ('follow', 'Follow'), ('comment', 'Comment'), ('share', 'Share')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for the activity')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.UUIDField(blank=True, null=True)),
                ('story_id', models.UUIDField(blank=True, null=True)),
                ('target_user_id', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='activities_user_id_timestamp_idx'), models.Index(fields=['activity_type', '-timestamp'], name='activities_activity_type_timestamp_idx'), models.Index(fields=['post_id'], name='activities_post_id_idx'), models.Index(fields=['target_user_id'], name='activities_target_user_id_idx')],
            },
        ),
    ]