# Generated by Django 5.0.1 on 2025-12-17 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("follow", "Follow"),
                            ("mention", "Mention"),
                            ("share", "Share"),
                            ("gift", "Gift"),
                            ("badge", "Badge Earned"),
                            ("level_up", "Level Up"),
                            ("system", "System"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title_template", models.CharField(max_length=200)),
                ("message_template", models.TextField(max_length=1000)),
                ("available_variables", models.JSONField(blank=True, default=list)),
                ("send_email", models.BooleanField(default=False)),
                ("send_push", models.BooleanField(default=True)),
                ("send_in_app", models.BooleanField(default=True)),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("premium", "Premium Users"),
                            ("active", "Active Users"),
                            ("inactive", "Inactive Users"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "notification template",
                "verbose_name_plural": "notification templates",
            },
        ),
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("target_segments", models.JSONField(blank=True, default=dict)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("unsubscribe_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="email_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "email campaign",
                "verbose_name_plural": "email campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("notifications_sent", models.PositiveIntegerField(default=0)),
                ("notifications_delivered", models.PositiveIntegerField(default=0)),
                ("push_tokens_active", models.PositiveIntegerField(default=0)),
                ("notifications_read", models.PositiveIntegerField(default=0)),
                ("notifications_clicked", models.PositiveIntegerField(default=0)),
                ("by_type", models.JSONField(blank=True, default=dict)),
                ("by_platform", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "notification analytics",
                "verbose_name_plural": "notification analytics",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_likes", models.BooleanField(default=True)),
                ("email_comments", models.BooleanField(default=True)),
                ("email_follows", models.BooleanField(default=True)),
                ("email_mentions", models.BooleanField(default=True)),
                ("email_gifts", models.BooleanField(default=True)),
                ("email_badges", models.BooleanField(default=True)),
                ("email_marketing", models.BooleanField(default=False)),
                ("email_weekly_digest", models.BooleanField(default=True)),
                ("push_likes", models.BooleanField(default=True)),
                ("push_comments", models.BooleanField(default=True)),
                ("push_follows", models.BooleanField(default=True)),
                ("push_mentions", models.BooleanField(default=True)),
                ("push_gifts", models.BooleanField(default=True)),
                ("push_badges", models.BooleanField(default=True)),
                ("push_system", models.BooleanField(default=True)),
                ("in_app_likes", models.BooleanField(default=True)),
                ("in_app_comments", models.BooleanField(default=True)),
                ("in_app_follows", models.BooleanField(default=True)),
                ("in_app_mentions", models.BooleanField(default=True)),
                ("in_app_gifts", models.BooleanField(default=True)),
                ("in_app_badges", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("follow", "Follow"),
                            ("mention", "Mention"),
                            ("share", "Share"),
                            ("gift", "Gift"),
                            ("badge", "Badge Earned"),
                            ("level_up", "Level Up"),
                            ("system", "System"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via_email", models.BooleanField(default=False)),
                ("sent_via_push", models.BooleanField(default=False)),
                ("sent_via_in_app", models.BooleanField(default=True)),
                ("group_key", models.CharField(blank=True, max_length=100)),
                ("is_grouped", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="social.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="content.post",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="content.story",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PushToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("app_version", models.CharField(blank=True, max_length=20)),
                ("os_version", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "push token",
                "verbose_name_plural": "push tokens",
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
