# Generated by Django 5.0.1 on 2025-12-17 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("reel", "Reel"),
                        ],
                        max_length=10,
                    ),
                ),
                ("caption", models.TextField(blank=True, max_length=2200)),
                ("media_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in seconds for videos",
                        null=True,
                    ),
                ),
                ("likes_count", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                ("views_count", models.IntegerField(default=0)),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("mentions", models.JSONField(blank=True, default=list)),
                ("location", models.JSONField(blank=True, null=True)),
                ("music_id", models.CharField(blank=True, max_length=100)),
                ("ai_caption", models.TextField(blank=True)),
                ("ai_tags", models.JSONField(blank=True, default=list)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="posts_user_id_dfa368_idx"
                    ),
                    models.Index(
                        fields=["post_type", "-created_at"],
                        name="posts_post_ty_2afc3b_idx",
                    ),
                    models.Index(
                        fields=["-likes_count"], name="posts_likes_c_a3a26f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("media_url", models.URLField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=10
                    ),
                ),
                ("duration", models.IntegerField(default=15)),
                ("views_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="stories_user_id_b336dc_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="stories_expires_a4b2b7_idx"
                    ),
                ],
            },
        ),
    ]
